language: csharp
dotnet: 2.2.301

sudo: false  # use the new container-based Travis infrastructure 

before_install:
  - chmod +x build.sh
 
script: 
  - mono ./.paket/paket.bootstrapper.exe
  - mono ./.paket/paket.exe restore # the docs depend on paket right now
  - dotnet build -c Release
  - ./docsrc/tools/generate.sh --define:RELEASE --define:REFERENCE
  - ./docsrc/tools/generate.sh --define:RELEASE --define:HELP
  - dotnet test -c Release
env:
  FSHARP_FORMATTING_LOG=NONE
