language: csharp
dotnet: 3.1.101

sudo: false  # use the new container-based Travis infrastructure 

script: 
  - dotnet restore ./FSharpPlus.sln
  - dotnet build -c Release ./FSharpPlus.sln
  - dotnet test -c Release tests/FSharpPlus.Tests
  - dotnet run -c Release --project ./docsrc/tools

env:
  FSHARP_FORMATTING_LOG=NONE