language: csharp
dotnet: 2.2.301

sudo: false  # use the new container-based Travis infrastructure 

before_install:
  - chmod +x build.sh
 
script: 
  - dotnet build -c Release
  - mono ./.paket/paket.bootstrapper.exe
  - mono ./.paket/paket.exe restore # the docs depend on paket right now
  - ./docsrc/tools/generate-reference.sh --define:RELEASE 
  - ./docsrc/tools/generate.sh --define:RELEASE
  - dotnet test -c Release
env:
  FSHARP_FORMATTING_LOG=NONE
