language: csharp
dotnet: 3.0.101

sudo: false  # use the new container-based Travis infrastructure 

before_install:
  - chmod +x build.sh
 
script: 
  - mono ./.paket/paket.bootstrapper.exe
  - mono ./.paket/paket.exe restore
  - dotnet build -c Release
  - dotnet test -c Release
env:
  FSHARP_FORMATTING_LOG=NONE
